version: "3.9"

services:
  postgres:
    platform: linux/amd64
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: bookstore

  mongo1:
    image: mongo:latest
    container_name: mongo1
    ports:
      - 27018:27017
    # command: --replSet rs
