version: "3.1"

volumes:
  dabase:
    driver: local

services:
  postgres:
    platform: linux/amd64
    image: postgres:14
    container_name: bookstore
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: bookstore
